__version__ = "2.2.0"
__app_name__ = "Apt"
__author__ = "Apt Contributors"
__description__ = "Find your perfect local LLM — scans hardware, recommends models, installs and chats"
__github_url__ = "https://github.com/Dkrynen/model-hub"
__download_url__ = "https://github.com/Dkrynen/model-hub/releases"
