/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env=staging --include-runtime=false --strict-vars=false env/worker-configuration.staging.d.ts` (hash: aa1dd421f010686bf7825942caeaf50c)
interface __BaseEnv_Env {
	R2_BUCKET: R2Bucket;
	PRO_GATE_RATE_LIMITER: RateLimit;
	CF_VERSION_METADATA: WorkerVersionMetadata;
	POLAR_ORG_ID: string;
	POLAR_API_BASE_URL: string;
	LOCAL_PRO_BENEFIT_ID: string;
	PRO_CLOUD_BENEFIT_ID: string;
	ENTITLEMENT_SIGNING_KID: string;
	ENTITLEMENT_SIGNING_PUBLIC_KEY: string;
	ARTIFACT_KEY: string;
	ARTIFACT_FILENAME: string;
	ARTIFACT_SHA256: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("../src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "POLAR_ORG_ID" | "POLAR_API_BASE_URL" | "LOCAL_PRO_BENEFIT_ID" | "PRO_CLOUD_BENEFIT_ID" | "ENTITLEMENT_SIGNING_KID" | "ENTITLEMENT_SIGNING_PUBLIC_KEY" | "ARTIFACT_KEY" | "ARTIFACT_FILENAME" | "ARTIFACT_SHA256">> {}
}
